### ISSUE TITLE
io.js needs 'use strict' when use class, let

### ISSUE THREAD

**Issue by yosuke-furukawa** [DJCordhose/ecmascript-2015-iojs#3]
We should expose the `use strict` on top of the following codes.

https://github.com/DJCordhose/ecmascript-2015-iojs/blob/master/workshop/step2-advanced/programmer-step2.js
https://github.com/DJCordhose/ecmascript-2015-iojs/blob/master/workshop/step2-advanced/programmer-step2b.js

Of course, I know you are put the `--use_strict` option on the `npm start` .
But it may be a trap when people bring the codes to their environment.

If you accept my suggestion, I will send a PR.

**Comment by DJCordhose** [comment]
Good catch, no need for a PR, I will just fix this. Thanks you :+1:

**Comment by yosuke-furukawa** [comment]
:+1:

**Comment by DJCordhose** [comment]
Closed by commit 40600fd38c205907248299b32b79139dd1c245e6
